### ISSUE TITLE
Issues with Webpack 2 

### ISSUE THREAD

**Issue by jmknoll** [akikoo/webpack-es6-sass-setup#1]
There are two errors in using this config with webpack 2

1) Breaking change to ExtractTextPlugin

> Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
> Example: if your old code looked like this:
>     ExtractTextPlugin.extract('style-loader', 'css-loader')
> 
> You would change it to:
>     ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })

2) Webpack config appears to be inconsistent with usage of post css and throws error: `configuration has an unknown property 'postcss'`.

See more info here: https://github.com/postcss/postcss-loader/issues/99

**Comment by akikoo** [comment]
Thanks @jmknoll - I see I neglected this issue for too long. Anyway, it should be fixed now.
